spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.jinyuanjava.litemall.core:  DEBUG
      # 默认日志文件名
      # file: log
      # 默认日志路径
      # path: ./log
    # logback.xml路径，默认为classpath:logback.xml
    # config: ./logback.xml
  file: myapp.log
